# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: windows-latest

steps:
  - task: Gradle@1
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.19'
      testResultsFiles: '**/build/test-results/TEST-*.xml'