# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: windows-latest

steps:
  - task: Gradle@1
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 'default' 
      #jdkVersionOption: 'default' # 'default' | '1.9' | '1.8' | '1.7' | '1.6'. Alias: jdkVersion. Optional. Use when javaHomeSelection = JDKVersion. JDK Version. Default: default.
      #publishJUnitResults: true # boolean. Publish to TFS/Team Services. Default: true.
      testResultsFiles: '**/build/test-results/TEST-*.xml'